import Home from "@Components/screens/home/Home";

import { NextPage } from "next";
import Head from "next/head";
import { IAnimeJikan } from "../src/store/animeJikan/IAnime.interface";

const HomePage: NextPage<IAnimeJikan> = () => {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Home />
		</>
	);
};

export default HomePage;
